In [1]:
import cipher_caesar
import cipher_rail
import cipher_vigenere
import pandas as pd

In [2]:
caesar = cipher_caesar.cipher_caesar()
rail = cipher_rail.cipher_rail()
vigenere = cipher_vigenere.cipher_vigenere()

# Decryptions
## Caesar/Shift Ciphers

In [3]:
str_text = '''MAX VHLM HY MAX UNL WKBOXK INGVA B NLXW MH INGVA FR HPG MKTGLYXKL''' 
df_ch01 = caesar.get_decrypts(str_txt_ciphered=str_text,is_try_reverse=False)
print(df_ch01.shape)
df_ch01.head()

(26, 4)

,shift,decrypted,percent_words,type
19,19,THE COST OF THE BUS DRIVER PUNCH I USED TO PUN...,0.928571,Caesar Forward
0,0,MAX VHLM HY MAX UNL WKBOXK INGVA B NLXW MH ING...,0.285714,Caesar Forward
5,5,HVS QCGH CT HVS PIG RFWJSF DIBQV W IGSR HC DIB...,0.214286,Caesar Forward
6,6,GUR PBFG BS GUR OHF QEVIRE CHAPU V HFRQ GB CHA...,0.214286,Caesar Forward
7,7,FTQ OAEF AR FTQ NGE PDUHQD BGZOT U GEQP FA BGZ...,0.214286,Caesar Forward

In [4]:
str_text = 'PBZFSOBP DKFOBTPKX LQ PBKFI PPBKFPRY AOXTOLC IIXZ LQ ABPR BOBT PBZFSBA CL BMVQ OBAIL BPBEQ'
df_ch03 = caesar.get_decrypts(str_txt_ciphered=str_text,is_try_reverse=True)
print(df_ch03.shape)
df_ch03.head()

(52, 4)

,shift,decrypted,percent_words,type
0,23,THESE OLDER TYPE OF DEVICES WERE USED TO CALL ...,0.733333,Caesar Reversed
26,8,HTRXKGTH VCXGTLHCP DI HTCXA HHTCXHJQ SGPLGDU A...,0.200000,Caesar Forward
1,11,FTQEQ AXPQD FKBQ AR PQHUOQE IQDQ GEQP FA OMXX ...,0.200000,Caesar Reversed
27,2,NZXDQMZN BIDMZRNIV JO NZIDG NNZIDNPW YMVRMJA G...,0.133333,Caesar Forward
2,3,NBYMY IFXYL NSJY IZ XYPCWYM QYLY OMYX NI WUFF ...,0.133333,Caesar Reversed

## Rail Ciphers

In [5]:
str_text = 'TI SATSHSI  ET'
df_test = rail.get_decrypts(str_txt_ciphered=str_text,val_n_rails=5)
df_test.head()

   shift       decrypted  percent_words  type
2      2  THIS IS A TEST           1.00  Rail
4      4  TSSEIAIT T S H           0.75  Rail
0      0  TI SATSHSI  ET           0.25  Rail
1      1  TI SATSHSI  ET           0.25  Rail
3      3  TA TISEH STIS            0.25  Rail

## Vigenere Ciphers

In [6]:
str_text = 'TI SATSHSI  ET'
vigenere.configure_random()
print(vigenere._val_key)
vigenere.msg_encrypt(str_text)

reascensional

'KM SSVWUKQ  SG'